[package]
name = "LegatoVault"
version = "0.2.0"
edition = "2024.beta"
published-at = "0xa2bddfde336d1e7c2f385d3009c815e18a204c127777f7c29f0c228db1e2b90f"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
SuiSystem = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-system", rev = "framework/testnet" }
LegatoMath = {  git = "https://github.com/tamago-labs/legato-math.git", subdir = "packages/sui", rev = "main"  }

[addresses]
legato = "0xa2bddfde336d1e7c2f385d3009c815e18a204c127777f7c29f0c228db1e2b90f"
