[package]
name = "legato"
version = "0.1.0"
authors = []

[addresses]
legato_addr = "f586bbdd187df4e3bd7cd5b8af8a7018d8b8b5f3ec24a95cd5ac79d94ebca981"
aptos_framework = "0x1"
aptos_fungible_asset = "0xA"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
