[package]
name = "legato"
version = "0.1.0"
authors = []

[addresses]
legato_addr = "07ea832095677f4cabe49e875d155d2ee3c36b9c7cfa66cad99c6e8e9f98c34b"
aptos_framework = "0x1"
aptos_fungible_asset = "0xA"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
