[package]
name = "legato-vault"
version = "0.2.0"
authors = []

[addresses]
legato_vault_addr = "45fa42f6840a7032a97d4d66a45a776be0b8d73bb54182cee82cc41cc7d9a962"
aptos_framework = "0x1"
aptos_fungible_asset = "0xA"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
